### ISSUE TITLE
Documentation on major differences from BVLC/caffe

### ISSUE THREAD

**Issue by venkai** [borisgin/nvcaffe#4]
Hi,

I recently migrated from BVLC/caffe to nvcaffe, and there is a significant speedup during inference.
The options for layer-specific mixed-precision support is awesome.
I would also like to use nvcaffe for training and I have a few questions:

1. There is an `enum Packing` in caffe.proto which can be set to `NCHW`(default) or `NHWC`. If we set Packing to `NHWC` in the data layer, will the packing info be automatically transmitted to all the layers in the network ? Intuitively, it feels as though `NHWC` should be more efficient for both convolution and batch-norm layers, particularly for CUDNN.
2. The data augmentations are a bit confusing. Are the transformations in data_transformer.cu carried out synchronously on the GPU or are they done asynchronously with the data prefetch threads ?
3. There is also another layer called detectnet_transform_layer.[hpp/cpp/cu] which has its own set of transformations. When/how exactly is this layer used ? In particular, I am interested in image-to-image translation problems where both input and label are images of the same size and we mirror the transformations (random crops, flips, scale, mean subtraction, etc) on both the input and label image. I was wondering if this layer could be used for that.
4. Is multi-GPU inference with a single large image possible ?
5. Is there some way to further reduce memory during inference for large images ? For fully convolutional architectures, a lot of memory can be saved for instance by not storing most of the intermediate layer activations and using a single buffer for most convolution layers.

Finally, if there is some specific documentation for nvcaffe, that would also be awesome.

**Comment by borisgin** [comment]
Hi Venkai,
1. I recommend to use https://github.com/NVIDIA/caffe. It is more clean and tested :)
2. I did not try NHWC format yet, so I can't tell if it is faster than default NCHW
3. About data augmentation: by default transform is done on CPU , but you can set it to GPU using use_gpu_transform: True in train_val.prototxt
4. Detectnet: see  https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/README.md 
5. inference in  multi-gpu mode: works as data-parallel - batch is divided between GPU-s, minimum 1 image /  GPU 
6. To reduce memory during inference: 
  1. if input and output buffer for layer have the same dimensions, do them in place. You can generate such val.prototxt using python scripts from models/model_builder 
  2. use fp16 data type 
      default_forward_type:  FLOAT16
  3. set parser thread to1:
       threads : 1 
       parser_threads: 1

**Comment by venkai** [comment]
@borisgin Thanks a lot for the response ! I will use [NVIDIA/caffe](https://github.com/NVIDIA/caffe) instead.
